**This is the first day of doing numpy**


In [1]:
import numpy as np


In [2]:
myarray=np.array([[3,6,32,7]],np.int8)

In [3]:
myarray

array([[ 3,  6, 32,  7]], dtype=int8)

In [4]:
myarray.shape


(1, 4)

In [5]:
myarray.dtype

dtype('int8')

In [6]:
myarray.itemsize


1

In [7]:
myarray[0,1]=33

In [8]:
myarray

array([[ 3, 33, 32,  7]], dtype=int8)

In [9]:
myarray*2

array([[ 6, 66, 64, 14]], dtype=int8)

**Array creation: conversion form other Python structures**

In [10]:
listarray=np.array([[1,2,3],[4,5,7],[2,0,4]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 7],
       [2, 0, 4]])

In [12]:
listarray.shape


(3, 3)

In [13]:
listarray.size

9

In [14]:
listarray.dtype

dtype('int64')

**Intrinsic numpy array creation objects(eg.arrange,ones,zeros etc)**


In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones=np.ones((3,5))

In [18]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
ones.shape

(3, 5)

In [20]:
ones.dtype

dtype('float64')

In [21]:
ones.size

15

In [22]:
arange=np.arange(15)

In [23]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
linspace=np.linspace(1,10,4)

In [25]:
linspace

array([ 1.,  4.,  7., 10.])

In [26]:
empty=np.empty((6,4))

In [27]:
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
empty_like=np.empty_like(linspace)

In [29]:
empty_like

array([ 1.,  4.,  7., 10.])

In [30]:
identity=np.identity((10))

In [31]:
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
identity.shape


(10, 10)

In [33]:
identity.dtype

dtype('float64')

In [34]:
rang=np.arange((99))

In [35]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
rangw=rang.reshape((3,33))

In [37]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
rangw

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
rang.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
rangw.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
rangw.shape



(3, 33)

In [43]:
rabgw=rangw.ravel()

In [44]:
rangw.shape

(3, 33)

In [45]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar=np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.flat

In [54]:
for number in ar.flat:
    print(number)

1
2
3
4
5
6
7
1
0


In [55]:
ar.ndim

2

In [56]:
ar.nbytes

72

In [57]:
one=np.array([1,2,3,634,4])

In [58]:
one.argmax()

np.int64(3)

In [59]:
one.argmin()

np.int64(0)

In [60]:
one.argsort()

array([0, 1, 2, 4, 3])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar.argmin()

np.int64(8)

In [63]:
ar.argmax()

np.int64(6)

In [64]:
ar.argmax(axis=0)

array([2, 1, 1])

In [65]:
ar.argmax(axis=1)

array([2, 2, 0])

In [66]:
ar.argmin(axis=0)

array([0, 2, 2])

In [67]:
ar.argmin(axis=1)

array([0, 0, 2])

In [68]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [69]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [70]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
[324,33]+[22,89]

[324, 33, 22, 89]

In [74]:
ar*ar2


array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [76]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [77]:
ar.sum()

np.int64(29)

In [78]:
ar.max()

np.int64(7)

In [79]:
ar.min()


np.int64(0)

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [82]:
np.where(ar<1)

(array([2]), array([2]))

In [83]:
np.count_nonzero(ar)

8

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [85]:
ar[1,0]=0


In [86]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 1, 2, 0, 1]))

In [87]:
import sys

In [88]:
char=[0,4,55,2]

In [89]:
np_ar=np.array(char)

In [90]:
sys.getsizeof(1)*len(char)

112

In [91]:
np_ar.itemsize*np_ar.size

32

In [93]:
char.ndim

AttributeError: 'list' object has no attribute 'ndim'